import { eq, inArray } from 'drizzle-orm';
import { roles, permissions, rolePermissions } from '../schema/iam';
import { PERMISSIONS, ROLES } from '@taralaya/shared';
import type { DbClient } from '../client';

// Permission matrix per Phase 10 §10.3
// Format: roleKey → permissionKey[]
const ROLE_PERMISSION_MATRIX: Record<string, string[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS), // all permissions

  [ROLES.ADMIN]: [
    PERMISSIONS.USER_VIEW, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE, PERMISSIONS.USER_MANAGE, PERMISSIONS.USER_PERMISSION_CHANGE,
    PERMISSIONS.USER_EXPORT,
    PERMISSIONS.ROLE_VIEW, PERMISSIONS.ROLE_CREATE, PERMISSIONS.ROLE_UPDATE,
    PERMISSIONS.ROLE_DELETE, PERMISSIONS.ROLE_PERMISSION_CHANGE,
    PERMISSIONS.PERMISSION_VIEW,
    PERMISSIONS.APIKEY_VIEW, PERMISSIONS.APIKEY_CREATE, PERMISSIONS.APIKEY_DELETE,
    PERMISSIONS.LEAD_VIEW, PERMISSIONS.LEAD_CREATE, PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_DELETE, PERMISSIONS.LEAD_MANAGE, PERMISSIONS.LEAD_EXPORT,
    PERMISSIONS.CLIENT_VIEW, PERMISSIONS.CLIENT_CREATE, PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.CLIENT_DELETE, PERMISSIONS.CLIENT_MANAGE, PERMISSIONS.CLIENT_EXPORT,
    PERMISSIONS.PRICELIST_VIEW, PERMISSIONS.PRICELIST_CREATE, PERMISSIONS.PRICELIST_UPDATE,
    PERMISSIONS.PRICELIST_DELETE,
    PERMISSIONS.QUOTATION_VIEW, PERMISSIONS.QUOTATION_CREATE, PERMISSIONS.QUOTATION_UPDATE,
    PERMISSIONS.QUOTATION_DELETE, PERMISSIONS.QUOTATION_APPROVE, PERMISSIONS.QUOTATION_MANAGE,
    PERMISSIONS.QUOTATION_EXPORT,
    PERMISSIONS.PROPOSAL_VIEW, PERMISSIONS.PROPOSAL_CREATE, PERMISSIONS.PROPOSAL_UPDATE,
    PERMISSIONS.PROPOSAL_DELETE, PERMISSIONS.PROPOSAL_APPROVE,
    PERMISSIONS.CONTRACT_VIEW, PERMISSIONS.CONTRACT_CREATE, PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_DELETE, PERMISSIONS.CONTRACT_APPROVE, PERMISSIONS.CONTRACT_MANAGE,
    PERMISSIONS.PROJECT_VIEW, PERMISSIONS.PROJECT_CREATE, PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE, PERMISSIONS.PROJECT_MANAGE, PERMISSIONS.PROJECT_APPROVE,
    PERMISSIONS.PROJECT_EXPORT,
    PERMISSIONS.TASK_VIEW, PERMISSIONS.TASK_CREATE, PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE, PERMISSIONS.TASK_TRANSITION,
    PERMISSIONS.INVOICE_VIEW, PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_DELETE, PERMISSIONS.INVOICE_APPROVE, PERMISSIONS.INVOICE_MANAGE,
    PERMISSIONS.INVOICE_EXPORT,
    PERMISSIONS.RECEIPT_VIEW, PERMISSIONS.RECEIPT_CREATE, PERMISSIONS.RECEIPT_UPDATE,
    PERMISSIONS.RECEIPT_DELETE,
    PERMISSIONS.EXPENSE_VIEW, PERMISSIONS.EXPENSE_CREATE, PERMISSIONS.EXPENSE_UPDATE,
    PERMISSIONS.EXPENSE_DELETE, PERMISSIONS.EXPENSE_APPROVE,
    PERMISSIONS.INCOME_VIEW, PERMISSIONS.INCOME_CREATE, PERMISSIONS.INCOME_UPDATE,
    PERMISSIONS.INCOME_DELETE,
    PERMISSIONS.PLAN_VIEW, PERMISSIONS.PLAN_CREATE, PERMISSIONS.PLAN_UPDATE, PERMISSIONS.PLAN_DELETE,
    PERMISSIONS.SUBSCRIPTION_VIEW, PERMISSIONS.SUBSCRIPTION_CREATE,
    PERMISSIONS.MCO_VIEW, PERMISSIONS.MCO_CREATE, PERMISSIONS.MCO_APPROVE, PERMISSIONS.MCO_MANAGE,
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_CREATE, PERMISSIONS.PAYROLL_UPDATE,
    PERMISSIONS.PAYROLL_APPROVE, PERMISSIONS.PAYROLL_DELETE, PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.PAYROLL_EXPORT, PERMISSIONS.PAYROLL_POST,
    PERMISSIONS.ASSET_VIEW, PERMISSIONS.ASSET_CREATE, PERMISSIONS.ASSET_UPDATE,
    PERMISSIONS.ASSET_DELETE, PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.NOTIFICATION_VIEW, PERMISSIONS.NOTIFICATION_CREATE, PERMISSIONS.NOTIFICATION_MANAGE,
    PERMISSIONS.ARTICLE_VIEW, PERMISSIONS.ARTICLE_CREATE, PERMISSIONS.ARTICLE_UPDATE,
    PERMISSIONS.ARTICLE_DELETE, PERMISSIONS.ARTICLE_APPROVE,
    PERMISSIONS.AUDIT_VIEW, PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.TAG_VIEW, PERMISSIONS.TAG_CREATE, PERMISSIONS.TAG_UPDATE, PERMISSIONS.TAG_DELETE,
    PERMISSIONS.REMINDER_VIEW, PERMISSIONS.REMINDER_CREATE, PERMISSIONS.REMINDER_UPDATE,
    PERMISSIONS.ATTACHMENT_VIEW, PERMISSIONS.ATTACHMENT_CREATE, PERMISSIONS.ATTACHMENT_DELETE,
    PERMISSIONS.COMMENT_VIEW, PERMISSIONS.COMMENT_CREATE, PERMISSIONS.COMMENT_UPDATE,
    PERMISSIONS.COMMENT_DELETE,
    PERMISSIONS.SETTING_VIEW, PERMISSIONS.SETTING_MANAGE,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.PERMISSION_VIEW,
    PERMISSIONS.LEAD_VIEW, PERMISSIONS.LEAD_MANAGE, PERMISSIONS.LEAD_EXPORT,
    PERMISSIONS.CLIENT_VIEW, PERMISSIONS.CLIENT_MANAGE, PERMISSIONS.CLIENT_EXPORT,
    PERMISSIONS.PRICELIST_VIEW,
    PERMISSIONS.QUOTATION_VIEW, PERMISSIONS.QUOTATION_APPROVE, PERMISSIONS.QUOTATION_MANAGE,
    PERMISSIONS.QUOTATION_EXPORT,
    PERMISSIONS.PROPOSAL_VIEW, PERMISSIONS.PROPOSAL_CREATE, PERMISSIONS.PROPOSAL_UPDATE,
    PERMISSIONS.PROPOSAL_APPROVE,
    PERMISSIONS.CONTRACT_VIEW, PERMISSIONS.CONTRACT_APPROVE, PERMISSIONS.CONTRACT_MANAGE,
    PERMISSIONS.PROJECT_VIEW, PERMISSIONS.PROJECT_CREATE, PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE, PERMISSIONS.PROJECT_MANAGE, PERMISSIONS.PROJECT_APPROVE,
    PERMISSIONS.PROJECT_EXPORT,
    PERMISSIONS.TASK_VIEW, PERMISSIONS.TASK_CREATE, PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE, PERMISSIONS.TASK_TRANSITION,
    PERMISSIONS.INVOICE_VIEW, PERMISSIONS.INVOICE_EXPORT,
    PERMISSIONS.RECEIPT_VIEW,
    PERMISSIONS.EXPENSE_VIEW, PERMISSIONS.EXPENSE_CREATE, PERMISSIONS.EXPENSE_UPDATE,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.ASSET_VIEW, PERMISSIONS.ASSET_CREATE, PERMISSIONS.ASSET_UPDATE,
    PERMISSIONS.ASSET_MANAGE,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE, PERMISSIONS.MAINTENANCE_UPDATE,
    PERMISSIONS.MAINTENANCE_APPROVE,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.ARTICLE_VIEW, PERMISSIONS.ARTICLE_CREATE, PERMISSIONS.ARTICLE_UPDATE,
    PERMISSIONS.ARTICLE_APPROVE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.TAG_VIEW, PERMISSIONS.TAG_CREATE, PERMISSIONS.TAG_UPDATE, PERMISSIONS.TAG_DELETE,
    PERMISSIONS.REMINDER_VIEW, PERMISSIONS.REMINDER_CREATE, PERMISSIONS.REMINDER_UPDATE,
    PERMISSIONS.ATTACHMENT_VIEW, PERMISSIONS.ATTACHMENT_CREATE, PERMISSIONS.ATTACHMENT_DELETE,
    PERMISSIONS.COMMENT_VIEW, PERMISSIONS.COMMENT_CREATE, PERMISSIONS.COMMENT_UPDATE,
    PERMISSIONS.MCO_VIEW, PERMISSIONS.MCO_MANAGE,
    PERMISSIONS.PLAN_VIEW, PERMISSIONS.SUBSCRIPTION_VIEW,
  ],

  [ROLES.SALES]: [
    PERMISSIONS.LEAD_VIEW, PERMISSIONS.LEAD_CREATE, PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_DELETE, PERMISSIONS.LEAD_MANAGE, PERMISSIONS.LEAD_EXPORT,
    PERMISSIONS.CLIENT_VIEW, PERMISSIONS.CLIENT_CREATE, PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.CLIENT_DELETE, PERMISSIONS.CLIENT_MANAGE, PERMISSIONS.CLIENT_EXPORT,
    PERMISSIONS.PRICELIST_VIEW, PERMISSIONS.PRICELIST_CREATE, PERMISSIONS.PRICELIST_UPDATE,
    PERMISSIONS.QUOTATION_VIEW, PERMISSIONS.QUOTATION_CREATE, PERMISSIONS.QUOTATION_UPDATE,
    PERMISSIONS.QUOTATION_DELETE, PERMISSIONS.QUOTATION_APPROVE, PERMISSIONS.QUOTATION_MANAGE,
    PERMISSIONS.QUOTATION_EXPORT,
    PERMISSIONS.PROPOSAL_VIEW, PERMISSIONS.PROPOSAL_CREATE, PERMISSIONS.PROPOSAL_UPDATE,
    PERMISSIONS.PROPOSAL_DELETE, PERMISSIONS.PROPOSAL_APPROVE,
    PERMISSIONS.CONTRACT_VIEW, PERMISSIONS.CONTRACT_CREATE, PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_DELETE, PERMISSIONS.CONTRACT_APPROVE, PERMISSIONS.CONTRACT_MANAGE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.INVOICE_VIEW, PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_APPROVE,
    PERMISSIONS.INVOICE_EXPORT,
    PERMISSIONS.PLAN_VIEW, PERMISSIONS.SUBSCRIPTION_VIEW, PERMISSIONS.SUBSCRIPTION_CREATE,
    PERMISSIONS.MCO_VIEW, PERMISSIONS.MCO_CREATE, PERMISSIONS.MCO_UPDATE,
    PERMISSIONS.MCO_APPROVE, PERMISSIONS.MCO_MANAGE,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.ARTICLE_VIEW, PERMISSIONS.ARTICLE_CREATE, PERMISSIONS.ARTICLE_UPDATE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.TAG_VIEW, PERMISSIONS.TAG_CREATE, PERMISSIONS.TAG_UPDATE, PERMISSIONS.TAG_DELETE,
    PERMISSIONS.REMINDER_VIEW, PERMISSIONS.REMINDER_CREATE, PERMISSIONS.REMINDER_UPDATE,
    PERMISSIONS.ATTACHMENT_VIEW, PERMISSIONS.ATTACHMENT_CREATE,
    PERMISSIONS.COMMENT_VIEW, PERMISSIONS.COMMENT_CREATE, PERMISSIONS.COMMENT_UPDATE,
  ],

  [ROLES.FINANCE]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.CLIENT_VIEW, PERMISSIONS.CLIENT_EXPORT,
    PERMISSIONS.PRICELIST_VIEW,
    PERMISSIONS.QUOTATION_VIEW, PERMISSIONS.QUOTATION_EXPORT,
    PERMISSIONS.CONTRACT_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.INVOICE_VIEW, PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_DELETE, PERMISSIONS.INVOICE_APPROVE, PERMISSIONS.INVOICE_MANAGE,
    PERMISSIONS.INVOICE_EXPORT,
    PERMISSIONS.RECEIPT_VIEW, PERMISSIONS.RECEIPT_CREATE, PERMISSIONS.RECEIPT_UPDATE,
    PERMISSIONS.RECEIPT_DELETE,
    PERMISSIONS.EXPENSE_VIEW, PERMISSIONS.EXPENSE_CREATE, PERMISSIONS.EXPENSE_UPDATE,
    PERMISSIONS.EXPENSE_DELETE, PERMISSIONS.EXPENSE_APPROVE,
    PERMISSIONS.INCOME_VIEW, PERMISSIONS.INCOME_CREATE, PERMISSIONS.INCOME_UPDATE,
    PERMISSIONS.INCOME_DELETE,
    PERMISSIONS.PLAN_VIEW, PERMISSIONS.SUBSCRIPTION_VIEW, PERMISSIONS.SUBSCRIPTION_UPDATE,
    PERMISSIONS.SUBSCRIPTION_DELETE, PERMISSIONS.SUBSCRIPTION_MANAGE,
    PERMISSIONS.MCO_VIEW, PERMISSIONS.MCO_CREATE, PERMISSIONS.MCO_UPDATE,
    PERMISSIONS.MCO_APPROVE, PERMISSIONS.MCO_MANAGE,
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_CREATE, PERMISSIONS.PAYROLL_UPDATE,
    PERMISSIONS.PAYROLL_APPROVE, PERMISSIONS.PAYROLL_DELETE, PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.PAYROLL_EXPORT, PERMISSIONS.PAYROLL_POST,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.ARTICLE_VIEW,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.TAG_VIEW, PERMISSIONS.TAG_CREATE, PERMISSIONS.TAG_UPDATE, PERMISSIONS.TAG_DELETE,
    PERMISSIONS.REMINDER_VIEW, PERMISSIONS.REMINDER_CREATE, PERMISSIONS.REMINDER_UPDATE,
    PERMISSIONS.ATTACHMENT_VIEW, PERMISSIONS.ATTACHMENT_CREATE,
    PERMISSIONS.COMMENT_VIEW, PERMISSIONS.COMMENT_CREATE,
  ],

  [ROLES.HR]: [
    PERMISSIONS.USER_VIEW, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE, PERMISSIONS.USER_MANAGE, PERMISSIONS.USER_PERMISSION_CHANGE,
    PERMISSIONS.USER_EXPORT,
    PERMISSIONS.ROLE_VIEW,
    PERMISSIONS.PERMISSION_VIEW,
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_CREATE, PERMISSIONS.PAYROLL_UPDATE,
    PERMISSIONS.PAYROLL_APPROVE, PERMISSIONS.PAYROLL_DELETE, PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.PAYROLL_EXPORT, PERMISSIONS.PAYROLL_POST,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.ARTICLE_VIEW,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.TAG_VIEW, PERMISSIONS.TAG_CREATE, PERMISSIONS.TAG_UPDATE, PERMISSIONS.TAG_DELETE,
    PERMISSIONS.REMINDER_VIEW, PERMISSIONS.REMINDER_CREATE, PERMISSIONS.REMINDER_UPDATE,
    PERMISSIONS.ATTACHMENT_VIEW, PERMISSIONS.ATTACHMENT_CREATE,
    PERMISSIONS.COMMENT_VIEW, PERMISSIONS.COMMENT_CREATE,
  ],

  [ROLES.DEVELOPER]: [
    PERMISSIONS.PROJECT_VIEW, PERMISSIONS.PROJECT_UPDATE, PERMISSIONS.PROJECT_EXPORT,
    PERMISSIONS.TASK_VIEW, PERMISSIONS.TASK_CREATE, PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_TRANSITION,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_CREATE, PERMISSIONS.MAINTENANCE_UPDATE,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.ARTICLE_VIEW, PERMISSIONS.ARTICLE_CREATE, PERMISSIONS.ARTICLE_UPDATE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.TAG_VIEW, PERMISSIONS.TAG_CREATE, PERMISSIONS.TAG_UPDATE, PERMISSIONS.TAG_DELETE,
    PERMISSIONS.REMINDER_VIEW, PERMISSIONS.REMINDER_CREATE, PERMISSIONS.REMINDER_UPDATE,
    PERMISSIONS.ATTACHMENT_VIEW, PERMISSIONS.ATTACHMENT_CREATE,
    PERMISSIONS.COMMENT_VIEW, PERMISSIONS.COMMENT_CREATE, PERMISSIONS.COMMENT_UPDATE,
  ],

  [ROLES.VIEWER]: [
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.PRICELIST_VIEW,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.CONTRACT_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.PLAN_VIEW,
    PERMISSIONS.SUBSCRIPTION_VIEW,
    PERMISSIONS.MCO_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.ARTICLE_VIEW,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.TAG_VIEW,
    PERMISSIONS.REMINDER_VIEW,
    PERMISSIONS.ATTACHMENT_VIEW,
    PERMISSIONS.COMMENT_VIEW,
  ],
};

export async function seedRolePermissions(db: DbClient) {
  console.log('  → Seeding role-permission matrix...');
  let count = 0;

  for (const [roleKey, permKeys] of Object.entries(ROLE_PERMISSION_MATRIX)) {
    const [roleRow] = await db
      .select({ id: roles.id })
      .from(roles)
      .where(eq(roles.key, roleKey))
      .limit(1);
    if (!roleRow) continue;

    const permRows = await db
      .select({ id: permissions.id, key: permissions.key })
      .from(permissions)
      .where(inArray(permissions.key, permKeys));

    for (const perm of permRows) {
      await db
        .insert(rolePermissions)
        .values({ roleId: roleRow.id, permissionId: perm.id })
        .onDuplicateKeyUpdate({ set: { roleId: roleRow.id } });
      count++;
    }
  }
  console.log(`     ✓ ${count} role-permission grants seeded`);
}
